version: "3"

tasks:
  generates:
    aliases:
      - gen
    desc: "Generating golang code from proto files"
    cmds:
      - protoc -I=proto/sso --go_out=gen/go/${proto_file_name} --go_opt=paths=source_relative --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative proto/sso/*.proto

